
name: "Ruby on Rails CI"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: testing_db_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:password@localhost:5432/testing_db_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: Proyecto-Testing-2024-1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
        working-directory: Proyecto-Testing-2024-1

      - name: Set up database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load
        working-directory: Proyecto-Testing-2024-1

      - name: Run MiniTest tests
        run: bundle exec rails test
        working-directory: Proyecto-Testing-2024-1

      - name: Run rspec tests
        if: success() || failure()
        run: bundle exec rspec
        working-directory: Proyecto-Testing-2024-1

      - name: Store coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: Proyecto-Testing-2024-1/coverage/
