name: "Ruby on Rails CI"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: testing_db_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:password@localhost:5432/testing_db_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: Proyecto-Testing-2024-1

      - name: Install Chrome and ChromeDriver
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f
          wget https://chromedriver.storage.googleapis.com/<<VERSION>>/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
        working-directory: Proyecto-Testing-2024-1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
        working-directory: Proyecto-Testing-2024-1

      - name: Set up database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load
        working-directory: Proyecto-Testing-2024-1

      - name: Run MiniTest tests
        run: bundle exec rails test
        working-directory: Proyecto-Testing-2024-1

      - name: Configure Selenium for Chrome headless
        run: |
          echo "Capybara.register_driver :selenium_chrome_headless do |app|" >> spec/rails_helper.rb
          echo "  Capybara::Selenium::Driver.new(app, browser: :chrome, options: Selenium::WebDriver::Chrome::Options.new(args: ['--headless', '--disable-gpu']))" >> spec/rails_helper.rb
          echo "end" >> spec/rails_helper.rb
          echo "" >> spec/rails_helper.rb
          echo "Capybara.default_driver = :selenium_chrome_headless" >> spec/rails_helper.rb
          echo "Capybara.javascript_driver = :selenium_chrome_headless" >> spec/rails_helper.rb
        working-directory: Proyecto-Testing-2024-1

      - name: Run rspec tests
        if: success() || failure()
        run: bundle exec rspec
        working-directory: Proyecto-Testing-2024-1

      - name: Store coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: Proyecto-Testing-2024-1/coverage/
